// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ts.proto

/*
Package timedot is a generated protocol buffer package.

It is generated from these files:
	ts.proto

It has these top-level messages:
	Timedot
	TimedotSave
	TimedotDelete
	Record
*/
package timedot

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Timedot struct {
	Year        int32 `protobuf:"varint,1,opt,name=year" json:"year,omitempty"`
	Month       int32 `protobuf:"varint,2,opt,name=month" json:"month,omitempty"`
	Date        int32 `protobuf:"varint,3,opt,name=date" json:"date,omitempty"`
	Hour        int32 `protobuf:"varint,4,opt,name=hour" json:"hour,omitempty"`
	Minute      int32 `protobuf:"varint,5,opt,name=minute" json:"minute,omitempty"`
	Second      int32 `protobuf:"varint,6,opt,name=second" json:"second,omitempty"`
	Microsecond int32 `protobuf:"varint,7,opt,name=microsecond" json:"microsecond,omitempty"`
}

func (m *Timedot) Reset()                    { *m = Timedot{} }
func (m *Timedot) String() string            { return proto.CompactTextString(m) }
func (*Timedot) ProtoMessage()               {}
func (*Timedot) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Timedot) GetYear() int32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *Timedot) GetMonth() int32 {
	if m != nil {
		return m.Month
	}
	return 0
}

func (m *Timedot) GetDate() int32 {
	if m != nil {
		return m.Date
	}
	return 0
}

func (m *Timedot) GetHour() int32 {
	if m != nil {
		return m.Hour
	}
	return 0
}

func (m *Timedot) GetMinute() int32 {
	if m != nil {
		return m.Minute
	}
	return 0
}

func (m *Timedot) GetSecond() int32 {
	if m != nil {
		return m.Second
	}
	return 0
}

func (m *Timedot) GetMicrosecond() int32 {
	if m != nil {
		return m.Microsecond
	}
	return 0
}

type TimedotSave struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *TimedotSave) Reset()                    { *m = TimedotSave{} }
func (m *TimedotSave) String() string            { return proto.CompactTextString(m) }
func (*TimedotSave) ProtoMessage()               {}
func (*TimedotSave) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TimedotSave) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type TimedotDelete struct {
	Success bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Count   uint64 `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
}

func (m *TimedotDelete) Reset()                    { *m = TimedotDelete{} }
func (m *TimedotDelete) String() string            { return proto.CompactTextString(m) }
func (*TimedotDelete) ProtoMessage()               {}
func (*TimedotDelete) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *TimedotDelete) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *TimedotDelete) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Record struct {
	TopicKey string     `protobuf:"bytes,1,opt,name=topicKey" json:"topicKey,omitempty"`
	TopicId  string     `protobuf:"bytes,2,opt,name=topicId" json:"topicId,omitempty"`
	Time     []*Timedot `protobuf:"bytes,3,rep,name=Time,json=time" json:"Time,omitempty"`
}

func (m *Record) Reset()                    { *m = Record{} }
func (m *Record) String() string            { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()               {}
func (*Record) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Record) GetTopicKey() string {
	if m != nil {
		return m.TopicKey
	}
	return ""
}

func (m *Record) GetTopicId() string {
	if m != nil {
		return m.TopicId
	}
	return ""
}

func (m *Record) GetTime() []*Timedot {
	if m != nil {
		return m.Time
	}
	return nil
}

func init() {
	proto.RegisterType((*Timedot)(nil), "timedot.Timedot")
	proto.RegisterType((*TimedotSave)(nil), "timedot.TimedotSave")
	proto.RegisterType((*TimedotDelete)(nil), "timedot.TimedotDelete")
	proto.RegisterType((*Record)(nil), "timedot.Record")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TimeFS service

type TimeFSClient interface {
	CreateTimedot(ctx context.Context, in *Record, opts ...grpc.CallOption) (*TimedotSave, error)
	ReadTimedot(ctx context.Context, in *Record, opts ...grpc.CallOption) (TimeFS_ReadTimedotClient, error)
	DeleteTimedot(ctx context.Context, in *Record, opts ...grpc.CallOption) (*TimedotDelete, error)
}

type timeFSClient struct {
	cc *grpc.ClientConn
}

func NewTimeFSClient(cc *grpc.ClientConn) TimeFSClient {
	return &timeFSClient{cc}
}

func (c *timeFSClient) CreateTimedot(ctx context.Context, in *Record, opts ...grpc.CallOption) (*TimedotSave, error) {
	out := new(TimedotSave)
	err := grpc.Invoke(ctx, "/timedot.TimeFS/CreateTimedot", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timeFSClient) ReadTimedot(ctx context.Context, in *Record, opts ...grpc.CallOption) (TimeFS_ReadTimedotClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_TimeFS_serviceDesc.Streams[0], c.cc, "/timedot.TimeFS/ReadTimedot", opts...)
	if err != nil {
		return nil, err
	}
	x := &timeFSReadTimedotClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TimeFS_ReadTimedotClient interface {
	Recv() (*Record, error)
	grpc.ClientStream
}

type timeFSReadTimedotClient struct {
	grpc.ClientStream
}

func (x *timeFSReadTimedotClient) Recv() (*Record, error) {
	m := new(Record)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *timeFSClient) DeleteTimedot(ctx context.Context, in *Record, opts ...grpc.CallOption) (*TimedotDelete, error) {
	out := new(TimedotDelete)
	err := grpc.Invoke(ctx, "/timedot.TimeFS/DeleteTimedot", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TimeFS service

type TimeFSServer interface {
	CreateTimedot(context.Context, *Record) (*TimedotSave, error)
	ReadTimedot(*Record, TimeFS_ReadTimedotServer) error
	DeleteTimedot(context.Context, *Record) (*TimedotDelete, error)
}

func RegisterTimeFSServer(s *grpc.Server, srv TimeFSServer) {
	s.RegisterService(&_TimeFS_serviceDesc, srv)
}

func _TimeFS_CreateTimedot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Record)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeFSServer).CreateTimedot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/timedot.TimeFS/CreateTimedot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeFSServer).CreateTimedot(ctx, req.(*Record))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimeFS_ReadTimedot_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Record)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TimeFSServer).ReadTimedot(m, &timeFSReadTimedotServer{stream})
}

type TimeFS_ReadTimedotServer interface {
	Send(*Record) error
	grpc.ServerStream
}

type timeFSReadTimedotServer struct {
	grpc.ServerStream
}

func (x *timeFSReadTimedotServer) Send(m *Record) error {
	return x.ServerStream.SendMsg(m)
}

func _TimeFS_DeleteTimedot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Record)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeFSServer).DeleteTimedot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/timedot.TimeFS/DeleteTimedot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeFSServer).DeleteTimedot(ctx, req.(*Record))
	}
	return interceptor(ctx, in, info, handler)
}

var _TimeFS_serviceDesc = grpc.ServiceDesc{
	ServiceName: "timedot.TimeFS",
	HandlerType: (*TimeFSServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTimedot",
			Handler:    _TimeFS_CreateTimedot_Handler,
		},
		{
			MethodName: "DeleteTimedot",
			Handler:    _TimeFS_DeleteTimedot_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReadTimedot",
			Handler:       _TimeFS_ReadTimedot_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ts.proto",
}

func init() { proto.RegisterFile("ts.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 320 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xcf, 0x6a, 0xf2, 0x40,
	0x14, 0xc5, 0xcd, 0x67, 0x4c, 0xf4, 0x06, 0xf9, 0xca, 0x45, 0x64, 0x70, 0x25, 0x43, 0xa1, 0xae,
	0xa4, 0xe8, 0xa6, 0x74, 0xd3, 0x45, 0x4b, 0xa1, 0x74, 0x37, 0xf6, 0x05, 0xd2, 0x99, 0x0b, 0x06,
	0x9a, 0x8c, 0x4c, 0x26, 0x05, 0x1f, 0xaa, 0xab, 0xbe, 0x60, 0x99, 0x3f, 0x4a, 0x09, 0xd8, 0xdd,
	0x3d, 0xbf, 0x39, 0x67, 0x3c, 0x73, 0x0d, 0x8c, 0x6d, 0xbb, 0x3e, 0x18, 0x6d, 0x35, 0xe6, 0xb6,
	0xaa, 0x49, 0x69, 0xcb, 0xbf, 0x12, 0xc8, 0xdf, 0xc2, 0x8c, 0x08, 0xe9, 0x91, 0x4a, 0xc3, 0x92,
	0x65, 0xb2, 0x1a, 0x09, 0x3f, 0xe3, 0x0c, 0x46, 0xb5, 0x6e, 0xec, 0x9e, 0xfd, 0xf3, 0x30, 0x08,
	0xe7, 0x54, 0xa5, 0x25, 0x36, 0x0c, 0x4e, 0x37, 0x3b, 0xb6, 0xd7, 0x9d, 0x61, 0x69, 0x60, 0x6e,
	0xc6, 0x39, 0x64, 0x75, 0xd5, 0x74, 0x96, 0xd8, 0xc8, 0xd3, 0xa8, 0x1c, 0x6f, 0x49, 0xea, 0x46,
	0xb1, 0x2c, 0xf0, 0xa0, 0x70, 0x09, 0x45, 0x5d, 0x49, 0xa3, 0xe3, 0x61, 0xee, 0x0f, 0x7f, 0x23,
	0x7e, 0x03, 0x45, 0xac, 0xbb, 0x2b, 0x3f, 0x09, 0x19, 0xe4, 0x6d, 0x27, 0x25, 0xb5, 0xad, 0x6f,
	0x3d, 0x16, 0x27, 0xc9, 0x1f, 0x60, 0x1a, 0x8d, 0x4f, 0xf4, 0x41, 0xf6, 0x0f, 0xab, 0x7b, 0xa3,
	0xd4, 0x5d, 0x63, 0xfd, 0x1b, 0x53, 0x11, 0x04, 0x57, 0x90, 0x09, 0x92, 0xda, 0x28, 0x5c, 0xc0,
	0xd8, 0xea, 0x43, 0x25, 0x5f, 0xe9, 0xe8, 0xa3, 0x13, 0x71, 0xd6, 0xee, 0x56, 0x3f, 0xbf, 0x28,
	0x9f, 0x9e, 0x88, 0x93, 0xc4, 0x6b, 0x48, 0x5d, 0x01, 0x36, 0x5c, 0x0e, 0x57, 0xc5, 0xe6, 0x6a,
	0x1d, 0x37, 0xbe, 0x8e, 0xad, 0x44, 0xea, 0xc0, 0xe6, 0x3b, 0x81, 0xcc, 0x91, 0xe7, 0x1d, 0xde,
	0xc1, 0xf4, 0xd1, 0x50, 0x69, 0xe9, 0xf4, 0x7f, 0xfc, 0x3f, 0x67, 0x42, 0x91, 0xc5, 0xac, 0x7f,
	0x89, 0xdb, 0x01, 0x1f, 0xe0, 0x16, 0x0a, 0x41, 0xa5, 0xba, 0x98, 0xeb, 0x03, 0x3e, 0xb8, 0x4d,
	0xf0, 0x1e, 0xa6, 0x61, 0x33, 0x17, 0x63, 0xf3, 0xfe, 0xcf, 0x05, 0x3f, 0x1f, 0xbc, 0x67, 0xfe,
	0x2b, 0xda, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0xc7, 0x3f, 0x0c, 0x94, 0x51, 0x02, 0x00, 0x00,
}
